services:
  
  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8000:8000"
    environment:
      - IMAGE_SERVICE_URL=http://image-service:8001
      - TEXT_SERVICE_URL=http://text-service:8002
      - CONTEXT_SERVICE_URL=http://context-service:8003
      - RISK_SERVICE_URL=http://risk-service:8004
      - FUSION_SERVICE_URL=http://fusion-service:8005
      - FEEDBACK_SERVICE_URL=http://feedback-service:8006
    depends_on:
      - image-service
      - text-service
      - context-service
      - risk-service
      - fusion-service
      - feedback-service
    networks:
      - crossmodal-network

  
  image-service:
    build: ./services/image-service
    ports:
      - "8001:8001"
    environment:
      - MODEL_CACHE_DIR=/app/models
    networks:
      - crossmodal-network

  text-service:
    build: ./services/text-service  
    ports:
      - "8002:8002"
    environment:
      - MODEL_CACHE_DIR=/app/models
    networks:
      - crossmodal-network

  context-service:
    build: ./services/context-service
    ports:
      - "8003:8003"
    networks:
      - crossmodal-network

  risk-service:
    build: ./services/risk-service
    ports:
      - "8004:8004"
    networks:
      - crossmodal-network

  fusion-service:
    build: ./services/fusion-service
    ports:
      - "8005:8005"
    networks:
      - crossmodal-network
  
  feedback-service:
    build: ./services/feedback-service
    ports: 
      - "8006:8006"
    environment:
      - AWS_REGION=us-east-1
    networks: 
      - crossmodal-network

  
  streamlit-dashboard:
    build: ./services/feedback-service
    ports:
      - "8501:8501"
    command: streamlit run app/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - API_GATEWAY_URL=http://orchestrator:8000
      - FEEDBACK_SERVICE_URL=http://feedback-service:8006
    depends_on:
      - orchestrator
      - feedback-service
    networks:
      - crossmodal-network

networks:
  crossmodal-network:
    driver: bridge