name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build microservices platform
      run: |
        cd ml-microservices-platform
        docker compose build
    
    - name: Start services and run health checks
      run: |
        cd ml-microservices-platform
        
        
        docker compose up -d
        
        
        echo "Waiting for services to be ready..."
        sleep 30
        
        
        echo "Checking service status:"
        docker compose ps
        
        
        echo "Testing orchestrator health..."
        curl -f http://localhost:8000/health || exit 1
        
        
        echo "Testing feedback service health..."
        curl -f http://localhost:8006/health || exit 1
        
        
        echo "Testing API documentation..."
        curl -f http://localhost:8000/docs || exit 1
    
    - name: Validate Docker containers
      run: |
        cd ml-microservices-platform
        echo "Validating all containers are healthy..."
        
        # Check if all expected containers are running
        running_containers=$(docker compose ps --services --filter "status=running")
        expected_services="orchestrator image-service text-service context-service risk-service fusion-service feedback-service"
        
        for service in $expected_services; do
          if echo "$running_containers" | grep -q "$service"; then
            echo "✅ $service is running"
          else
            echo "❌ $service is not running"
            exit 1
          fi
        done
        
        echo "All services are running correctly!"